# Generated by Django 5.1.6 on 2025-11-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='uploads/', verbose_name='Rezyume')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin havolasi')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram havolasi')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram havolasi')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub havolasi')),
                ('email', models.EmailField(default='admin@example.com', max_length=254, verbose_name='Elektron pochta manzili')),
                ('phone', models.CharField(default='+998901234567', max_length=13, verbose_name='Telefon raqam')),
                ('address', models.CharField(default="O'zbekiston, Toshkent", max_length=100, verbose_name='Uy manzili')),
            ],
            options={
                'verbose_name': "Ma'lumot ",
                'verbose_name_plural': "Ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Texnalogiya ',
                'verbose_name_plural': 'Texnalogiyalar',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('description', models.CharField(max_length=100, verbose_name='Tavsifi')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Rasmi')),
                ('demo', models.URLField(blank=True, null=True, verbose_name='Demo havolasi')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('technologies', models.ManyToManyField(related_name='portfolio', to='config.technology', verbose_name='Texnalogiyasi')),
            ],
            options={
                'verbose_name': 'Loyiha ',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
    ]
